Fix: try catch console errors
xerial-games/marketplace-web3-sdk pull request #19
Opened 2024-02-05 17:40 UTC by RichardIrala

2024-02-05 20:40 UTC, luislucena16 requested changes

2024-02-05 20:40 UTC, luislucena16 commented on atoms/XerialWallet/XerialWallet.jsx
> +      console.error("Error to copy text. Reason: ", err.message);
without the comma (`,`) for all would be fine...

2024-02-05 20:40 UTC, luislucena16 commented on functions/web3/web3.js
> +    console.error("Error to purchase NFT in Secondary Market. Reason: ", error.message);
how would you set the logs with function names or with descriptive names for you, define one... example:
error structure:
1. function with message + error
2. message + error

choose the best one for your development!

2024-02-07 21:00 UTC, RichardIrala commented on functions/web3/web3.js
> +    console.error("Error to purchase NFT in Secondary Market. Reason: ", error.message);
Done

2024-02-07 21:00 UTC, RichardIrala commented on atoms/XerialWallet/XerialWallet.jsx
> +      console.error("Error to copy text. Reason: ", err.message);
Done

2024-02-07 21:35 UTC, luislucena16 approved these changes

2024-02-07 21:35 UTC, merged