Feature/shopping cart
xerial-games/marketplace-web3-sdk pull request #29
Opened 2024-02-12 16:06 UTC by RichardIrala

Files changed:
* atoms/Item/Item.jsx
* functions/web2/web2.js
* functions/web3/web3.js
* pages/inventory.js
* web3-abis/marketplaceAbi.js

Feature ready. It shouldn't be merged until everything is synchronized and deployed on the xerial API

2024-02-13 13:11 UTC, luislucena16 requested changes

2024-02-13 13:11 UTC, luislucena16 commented on atoms/Item/Item.jsx
> +            quantity: amount,
great! this was the change we talked about, `quantity` is more clear with the function 👍

2024-02-13 13:11 UTC, luislucena16 commented on functions/web3/web3.js
> +    const marketplaceAddress = "0x77533EA81cd5CAAeE87E1D489261B4B1740DfAd2";
comment on this and uncomment the above line, no hardcode values, set it in `.env`

2024-02-13 13:11 UTC, luislucena16 commented on pages/inventory.js
> +      console.error("error to load playerItemsOnSecondaryMarket")
rename word `error` to `Error`

2024-02-13 16:44 UTC, RichardIrala commented on functions/web3/web3.js
> +    const marketplaceAddress = "0x77533EA81cd5CAAeE87E1D489261B4B1740DfAd2";
Done

2024-02-13 16:45 UTC, RichardIrala commented on pages/inventory.js
> +      console.error("error to load playerItemsOnSecondaryMarket")
Done

2024-02-13 17:54 UTC, luislucena16 commented
all good now! this PR is not yet finalised! we will still be checking

2024-02-13 18:02 UTC, luislucena16 commented on functions/web3/web3.js
> +    const purchaseTransaction = await marketplace.connect(signer).primaryPurchase([{ tokenTypeId, quantity, collectionAddress }]);
I don't see this! good job!

2024-02-14 15:41 UTC, luislucena16 requested changes

2024-02-14 15:41 UTC, luislucena16 commented on functions/web3/web3.js
> +web3Functions.purchaseNfts = async function (nfts) {
add a descriptive comment in this function

2024-02-14 15:41 UTC, luislucena16 commented on functions/web3/web3.js
> +web3Functions.purchaseNft = async function ({ tokenTypeId, quantity, collectionAddress }) {
add a descriptive comment in this function

2024-02-14 15:53 UTC, RichardIrala commented on functions/web3/web3.js
> +web3Functions.purchaseNfts = async function (nfts) {
Done

2024-02-14 15:53 UTC, RichardIrala commented on functions/web3/web3.js
> +web3Functions.purchaseNft = async function ({ tokenTypeId, quantity, collectionAddress }) {
Done

2024-02-14 16:02 UTC, luislucena16 approved these changes

2024-02-14 16:02 UTC, merged