Feature: support telos
xerial-games/marketplace-web3-sdk pull request #30
Opened 2024-02-16 20:56 UTC by RichardIrala

2024-02-19 19:00 UTC, luislucena16 requested changes

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +import getAddEthereumChainParam from "@/utils/addEthereumChainParams";
`getAdd` ? maybe you can use a better naming convention here, what do you think?

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
>    if (!globalThis.ethereum) throw Error("There is no ethereum in window / MetaMask is not installed");
are you asking about `ethereum` or is it related to `EVM` chains?

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +    console.error("Error verifying the Telos Network. Reason: ", error.message);
check these exceptions, we will use them like the previous one? with the `+` symbol.

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +    console.error("Error verifying the Telos Network. Reason: ", error.message);
check all error logs..

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.error("Error to add Telos tesnet network. Reason: ", error);
rename to this `Telos Test Network`

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Mumbai network");
rename to this `Polygon Test Network`

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.error("Error to add Mumbai network. Reason: ", error);
rename to this `Polygon Test Network`

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +    if (!usdcAddress) throw new Error("USDC address is invalid");
use this `USDC Address Is Invalid`

2024-02-19 19:00 UTC, luislucena16 commented on functions/web3/web3.js
> +    else purchaseTransaction = await marketplace.connect(signer).secondaryPurchase(marketplaceNftId, { gasLimit: telosGasLimit });
what's the price of `gasLimit` used here? maybe you can leave a comment with the value related to this.. what do you think?

2024-02-19 19:00 UTC, luislucena16 commented on pages/index.js
> +    XerialWalletViewmodel.loadProject();
why you rename this? just asking if this is the best way for you to work on the other files

2024-02-19 19:00 UTC, luislucena16 commented on pages/inventory.js
> +      console.error("Error in loadInventoryInTelos function. Reason: " +  error.message);
this is the error structure I am referring to!

2024-02-19 19:00 UTC, luislucena16 commented on pages/inventory.js
> +      console.error("Error to load playerItemsOnSecondaryMarket")
fixed this: `Error to load playerItemsOnSecondaryMarketInTelos function. Reason: " +  error.message);`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainId: null,
why chainId is `null` ? why don't use the real chainId?

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainId: null,
why chainId is `null` ? why don't use the real chainId?

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainName: "Mumbai Testnet",
use `Polygon Test Network`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainId: null,
why chainId is `null` ? why don't use the real chainId?

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainName: "Telos testnet",
use `Telos Test Network`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +				name: "TLOS",
the name is `TELOS` .. `TLOS` is the symbol

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +				name: "MATIC",
name is: `Polygon`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +				name: "MATIC",
name is `Polygon`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainId: null,
why chainId is `null` ? why don't use the real chainId?

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +			chainName: "Telos EVM Mainnet",
rename to this: `Telos Mainnet`

2024-02-19 19:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +				name: "TLOS",
name is `TELOS`

2024-02-19 19:00 UTC, luislucena16 commented on utils/telosGasLimit.js
> +const telosGasLimit = 5000000;
great, this is the value I mentioned, you could leave it in a comment where you use the variable to quickly recognize the value it uses

2024-02-19 19:00 UTC, luislucena16 commented on viewmodels/xerialWallet.js
>    vm.sessionToken = "";
what does this do?

2024-02-19 19:00 UTC, luislucena16 commented on viewmodels/xerialWallet.js
> +      // Quiza esto necesite el projectId <= (Revisar).
improve `REVIEW` comments, use this structure:
```bash
// REVIEW: maybe this needs the projectId
```

2024-02-19 19:08 UTC, luislucena16 requested changes

2024-02-19 19:08 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Telos Network");
rename to this `Telos Test Network`

2024-02-19 19:08 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +		{
format this please :')

2024-02-19 19:08 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +	if (!addEthereumChainParam) throw new Error("addEthereumChainParam Is Invalid");
maybe you can use a better Error message here

2024-02-19 19:08 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +	if (chain === defaultTelosChainValue && environment === "staging") addEthereumChainParam = addEthereumChainParams.telosTesnet;
in the end when you call the methods it will look much better this way:

```javascript
addEthereumChainParams.polygon
addEthereumChainParams.polygonTest
addEthereumChainParams.telos
addEthereumChainParams.telosTest
```

2024-02-19 19:10 UTC, luislucena16 commented
hey @RichardIrala I have left all my comments and focused on the `addEthereumChainParams.js` module that we have discussed ..!

2024-02-19 19:18 UTC, luislucena16 requested changes

2024-02-19 19:18 UTC, luislucena16 commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
maybe it can be confusing here because they both say `Polygon Network`, so in the one where the user is not on `Mainnet` let's put: `Polygon Test Network` when the user in not in `Mainnet`

2024-02-19 19:18 UTC, luislucena16 commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
the same for others where it is used

2024-02-19 19:21 UTC, RichardIrala commented on functions/web3/web3.js
> +import getAddEthereumChainParam from "@/utils/addEthereumChainParams";
"addEthereumChainParam" is the variable name because it is used for that action. The "get" refers to obtaining that parameter for that purpose.

2024-02-19 19:21 UTC, RichardIrala commented on functions/web3/web3.js
> +import getAddEthereumChainParam from "@/utils/addEthereumChainParams";
Could you suggest something better?

2024-02-19 19:24 UTC, RichardIrala commented on functions/web3/web3.js
>    if (!globalThis.ethereum) throw Error("There is no ethereum in window / MetaMask is not installed");
I search Ethereum in the UI because it's directly related to MetaMask, and it's the way to check if it's installed in the UI.

2024-02-19 19:27 UTC, RichardIrala commented on functions/web3/web3.js
> +    console.error("Error verifying the Telos Network. Reason: ", error.message);
Fixed. Thank you!

2024-02-19 19:27 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Mumbai network");
My bad, I will rewrite this. But with different content

2024-02-19 19:34 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +			chainName: "Telos EVM Mainnet",
Done

2024-02-19 19:35 UTC, RichardIrala commented on functions/web3/web3.js
> +    if (!usdcAddress) throw new Error("USDC address is invalid");
Done!

2024-02-19 19:36 UTC, RichardIrala commented on functions/web3/web3.js
> +    else purchaseTransaction = await marketplace.connect(signer).secondaryPurchase(marketplaceNftId, { gasLimit: telosGasLimit });
It's in its respective module. I don't mention it because it's there, and someday its value could change in its module.

2024-02-19 19:38 UTC, RichardIrala commented on pages/index.js
> +    XerialWalletViewmodel.loadProject();
Because I stopped using that instance and started injecting it from another component.

2024-02-19 19:40 UTC, RichardIrala commented on pages/inventory.js
> +      console.error("Error to load playerItemsOnSecondaryMarket")
Thaaaanks! Done

2024-02-19 19:41 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +			chainName: "Mumbai Testnet",
Why? If the network is Mumbai. Could you explain?

2024-02-19 19:41 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +				name: "TLOS",
Are you sure? I found it like this in several places.

2024-02-19 19:42 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +				name: "MATIC",
The native currency is Matic, am I wrong?

2024-02-19 19:42 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +				name: "MATIC",
The native currency is Matic, am I wrong?

2024-02-19 19:43 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +				name: "TLOS",
Are you sure? I found it like this in several places.

2024-02-19 19:44 UTC, RichardIrala commented on viewmodels/xerialWallet.js
>    vm.sessionToken = "";
This is done for the tests. Everything should be like this, with all the values. But at some point during refactors, I will add absolutely all of them. They are used as the initial state of the viewmodel, and it also serves for testing with JEST in our case.

2024-02-19 19:45 UTC, RichardIrala commented on viewmodels/xerialWallet.js
> +      // Quiza esto necesite el projectId <= (Revisar).
😢sorry. I didn't see this

2024-02-19 19:45 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Telos Network");
Hi, I delete "test" references

2024-02-19 19:46 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +		{
Done!

2024-02-19 19:46 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +	if (!addEthereumChainParam) throw new Error("addEthereumChainParam Is Invalid");
What do you recommend?

2024-02-19 19:47 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +	if (chain === defaultTelosChainValue && environment === "staging") addEthereumChainParam = addEthereumChainParams.telosTesnet;
sure, I will change this

2024-02-19 19:48 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +	if (chain === defaultTelosChainValue && environment === "staging") addEthereumChainParam = addEthereumChainParams.telosTesnet;
Done!

2024-02-19 19:54 UTC, RichardIrala commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
It's on purpose because the code itself is designed for Mainnet, and it's not necessary for the testnet where we develop. Otherwise, I would have to make the whole process dynamic. What do you think, do you agree?

2024-02-19 20:03 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.error("Error to add Telos tesnet network. Reason: ", error);
Done

2024-02-19 20:10 UTC, RichardIrala commented
Question: why chainId is "null" ? why don't use the real chainId?
Answer: I'm setting the chainId with a function. It's in the code. If you need any modifications, let me know, and I'll make them!

2024-02-20 13:42 UTC, luislucena16 requested changes

2024-02-20 13:42 UTC, luislucena16 commented on functions/web3/web3.js
> +import getAddEthereumChainParam from "@/utils/addEthereumChainParams";
hey @RichardIrala it could go either of these two ways:
- maybe it could be:

1. `ethereumChainParams` and when you need to fetch it if you use the `get` as this is already inferred from the context.

2. `addAndRetrieveEthereumChainParams`: This clearly indicates that the function adds the parameters and then retrieves them.

choose the right one for your use from the front!

2024-02-20 13:42 UTC, luislucena16 commented on functions/web3/web3.js
>    if (!globalThis.ethereum) throw Error("There is no ethereum in window / MetaMask is not installed");
perfect! that's what I thought!

2024-02-20 13:42 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Telos Network");
this section should be `Telos Mainnet`, right ?

2024-02-20 13:42 UTC, luislucena16 commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
from my point of view it would be a bit confusing because of the names that are repeated..

2024-02-20 13:42 UTC, luislucena16 commented on functions/web3/web3.js
> +    else purchaseTransaction = await marketplace.connect(signer).secondaryPurchase(marketplaceNftId, { gasLimit: telosGasLimit });
yes, I see it! great

2024-02-20 13:42 UTC, luislucena16 commented on pages/index.js
> +    XerialWalletViewmodel.loadProject();
nice! understood!!

2024-02-20 13:42 UTC, luislucena16 commented on viewmodels/xerialWallet.js
>    vm.sessionToken = "";
good explanation! it's clear to me!

2024-02-20 13:53 UTC, luislucena16 commented
> Question: why chainId is "null" ? why don't use the real chainId? Answer: I'm setting the chainId with a function. It's in the code. If you need any modifications, let me know, and I'll make them!

hey @RichardIrala for me it would look a bit better if we add it and it doesn't affect too much the logic you already have. Would it even be better for you, or how would you feel comfortable?

2024-02-20 13:55 UTC, luislucena16 requested changes

2024-02-20 13:55 UTC, luislucena16 commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Mumbai network");
great, mm what content should it have? with the one I tell you or another one?

2024-02-20 14:00 UTC, luislucena16 requested changes

2024-02-20 14:00 UTC, luislucena16 commented on viewmodels/xerialWallet.js
> -      // Quiza esto necesite el projectId <= (Revisar).
this `REVIEW` no longer needs to be checked?

2024-02-20 14:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +        name: "TLOS",
name is `TELOS`

2024-02-20 14:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +      chainName: "Telos testnet",
use `Telos Test`

2024-02-20 14:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +      chainName: "Mumbai Testnet",
use `Polygon Test`

2024-02-20 14:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +        name: "MATIC",
name is `Polygon`

2024-02-20 14:00 UTC, luislucena16 commented on utils/addEthereumChainParams.js
> +        name: "MATIC",
name is `Polygon`

2024-02-20 14:46 UTC, RichardIrala commented on functions/web3/web3.js
> +import getAddEthereumChainParam from "@/utils/addEthereumChainParams";
Done

2024-02-20 14:46 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Mumbai network");
"The user has been asked to add the Polygon Network"

2024-02-20 14:47 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Mumbai network");
I used that

2024-02-20 14:49 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +			chainName: "Telos testnet",
Done

2024-02-20 14:49 UTC, RichardIrala commented on viewmodels/xerialWallet.js
> +      // Quiza esto necesite el projectId <= (Revisar).
Deleted comment

2024-02-20 14:50 UTC, RichardIrala commented on functions/web3/web3.js
> +        console.log("The user has been asked to add the Telos Network");
It can be Telos testnet or Telos mainnet, depending on the type of deployment. That's why I don't specify anything. What do you think?

2024-02-20 14:52 UTC, RichardIrala commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
I don't understand

2024-02-20 14:54 UTC, RichardIrala commented
> > Question: why chainId is "null" ? why don't use the real chainId? Answer: I'm setting the chainId with a function. It's in the code. If you need any modifications, let me know, and I'll make them!
> 
> hey @RichardIrala for me it would look a bit better if we add it and it doesn't affect too much the logic you already have. Would it even be better for you, or how would you feel comfortable?

Ok, I will add these changes

2024-02-20 15:01 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +        name: "MATIC",
It's MATIC

2024-02-20 15:02 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +        name: "MATIC",
It's MATIC

2024-02-20 15:02 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +      chainName: "Mumbai Testnet",
Done

2024-02-20 15:03 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +      chainName: "Telos testnet",
Done

2024-02-20 15:03 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +        name: "TLOS",
It's TLOS. That name isn't the network name

2024-02-20 15:04 UTC, RichardIrala commented on viewmodels/xerialWallet.js
> -      // Quiza esto necesite el projectId <= (Revisar).
I think I already reviewed it

2024-02-20 17:29 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +	if (!addEthereumChainParam) throw new Error("addEthereumChainParam Is Invalid");
Done!

2024-02-20 17:30 UTC, RichardIrala commented on functions/web3/web3.js
> +      console.log("User is not on the Polygon Network");
Done!

2024-02-20 17:38 UTC, luislucena16 approved these changes, later dismissed
approve!! LGTM!

2024-02-20 17:43 UTC, nachopiris approved these changes

2024-02-20 17:44 UTC, luislucena16 approved these changes
LGTM!!

2024-02-20 17:44 UTC, RichardIrala commented on utils/addEthereumChainParams.js
> +				name: "MATIC",
Solve!

2024-02-20 17:45 UTC, merged